import { AuthProvider } from './components/AuthProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to acers',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
