import { DashboardAside } from './components/DashboardAside';
import Header from './components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex gap-2">
          <DashboardAside />

          {children}
        </div>
      </body>
    </html>
  );
}
